/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AchievementSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'iconUrl',
    'id',
    'name',
    'type',
    'updatedAt',
  ] as const
  $columns = AchievementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare iconUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ArchitecturePointSchema extends BaseModel {
  static $columns = [
    'address',
    'category',
    'createdAt',
    'description',
    'dynasty',
    'id',
    'imageUrl',
    'latitude',
    'longitude',
    'name',
    'updatedAt',
  ] as const
  $columns = ArchitecturePointSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare dynasty: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare latitude: string
  @column()
  declare longitude: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class KnowledgeNodeSchema extends BaseModel {
  static $columns = [
    'comparisons',
    'content',
    'createdAt',
    'id',
    'title',
    'type',
    'updatedAt',
  ] as const
  $columns = KnowledgeNodeSchema.$columns
  @column()
  declare comparisons: any | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class KnowledgeRelationSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'relationType',
    'sourceId',
    'targetId',
    'updatedAt',
  ] as const
  $columns = KnowledgeRelationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare relationType: string | null
  @column()
  declare sourceId: number | null
  @column()
  declare targetId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LearningRecordSchema extends BaseModel {
  static $columns = [
    'architecturePointId',
    'createdAt',
    'id',
    'isCheckedIn',
    'masteryLevel',
    'radarData',
    'updatedAt',
    'userId',
  ] as const
  $columns = LearningRecordSchema.$columns
  @column()
  declare architecturePointId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCheckedIn: boolean | null
  @column()
  declare masteryLevel: number | null
  @column()
  declare radarData: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
}

export class UserAchievementSchema extends BaseModel {
  static $columns = ['achievementId', 'id', 'unlockedAt', 'userId'] as const
  $columns = UserAchievementSchema.$columns
  @column()
  declare achievementId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare unlockedAt: DateTime
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'level',
    'passwordHash',
    'studyDays',
    'updatedAt',
    'userKnowledgeRadar',
    'userMedals',
    'username',
    'wechatOpenid',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: number
  @column()
  declare passwordHash: string | null
  @column()
  declare studyDays: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userKnowledgeRadar: any | null
  @column()
  declare userMedals: any | null
  @column()
  declare username: string | null
  @column()
  declare wechatOpenid: string | null
}
